### PR TITLE
Let users press modifier keys when clicking links and buttons

### PR DESCRIPTION
**Pull request by riazaia**
I already can't remember why I did it for the buttons, but I believe it's something to do with wanting it to work for thread views?

### CODE REVIEW

**Comment by riazaia** [comment]
Forgot to say, this refers to #71

**Review by essential-randomness — APPROVED** [review]

**Comment by essential-randomness** [comment]
Actually, I don't know that we need it for buttons at all. We only get buttons if there's no `href`, and if there's no `href` then there's no "default click-on-url" behavior. So I'd remove that change, tbh.

**Review by essential-randomness — CHANGES_REQUESTED** [review]
I'd remove it from button, as discussed :P

**Comment by riazaia** [comment]
Okay, I was trying to be lazy and resolving the conflict on github but that didnt work heh

**Comment by riazaia** [comment]
> Okay, I was trying to be lazy and resolving the conflict on github but that didnt work heh

and then i misclicked and accidentaly closed the PR fghjk

**Review by essential-randomness — APPROVED** [review]

**Pull request merged**
