### PR TITLE
Fix bug showing the bottombar when it shouldn't

### PR DESCRIPTION
**Pull request by riazaia**

### CODE REVIEW

**Comment by riazaia** [comment]
We should also change the property `desktopOnly` to `mobileOnly` since its currently backwards :3

**Review by essential-randomness — APPROVED** [review]
Revert yarn.lock and feel free to merge :)

**Comment by riazaia** [comment]
> Revert yarn.lock and feel free to merge :)

I don't know how to do that 😢

**Comment by riazaia** [comment]
Nevermind! I am a git genius

**Pull request merged**
